apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "paperless-ngx.fullname" . }}
  labels:
    {{- include "paperless-ngx.labels" . | nindent 4 }}
data:
  POSTGRESQL_SSLMODE: {{ .Values.postgresql.sslmode }}
  POSTGRESQL_HOST: {{ .Values.postgresql.host }}
  POSTGRESQL_PORT: {{ .Values.postgresql.port | quote }}
  POSTGRESQL_DATABASE: {{ .Values.postgresql.database }}
  POSTGRESQL_USERNAME: {{ .Values.postgresql.username | quote }}
  PAPERLESS_URL: {{ .Values.paperless.url }}
