apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "paperless-ngx.fullname" . }}
  labels:
    {{- include "paperless-ngx.labels" . | nindent 4 }}
data:
  REDIS_CONNECTION_STRING: {{ include "paperless-ngx.redisConnectionString" . | b64enc }}
  POSTGRESQL_PASSWORD: {{ .Values.postgresql.password | b64enc }}
  PAPERLESS_ADMIN_PASSWORD: {{ .Values.paperless.admin.password | b64enc }}
